# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a56283408b64048e57db1c82f34321ccd49fe87516082f9897a4c67f86a56221db2458cc0f8af4b8cb0c954056e03213965d0d2de61966da0432ad5c1d412f3

test:
  secret_key_base: a99535424b6464e93d7fdfee71cfa01e6178accb1d9250da64a77cad0cea46c6bcb668430666b20ba1fa4fe23aea07d72be3e804b1a33d77605c841a819dad2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
